#%RAML 1.0 DataType
type: object
properties:
 empId: 
  type: string
  minLength: 5
 nationalIDNumber: 
  type: string
  minLength: 11
  maxLength: 11
 eName: string
 addressLn: string
 addressCity: string
 addressZIP: string
 addressState: string
 addressCountry: string
 phone: string
 gender:
  type: string
  enum:
   - Male
   - Female
 birthDate:
  type: date-only